[package]
name = "hellorust"
version = "0.1.0"
authors = ["kennycaiguo <kennycai8888@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
